name: Secret Scan (TruffleHog)

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  trufflehog-scan:
    name: Run TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to scan full git history

      - name: Run TruffleHog on repository
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      # Optional: Comment result to PR if secrets are found
      - name: Report result to PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const message = `
            🚨 **TruffleHog Secret Scan Failed!**

            Verified secrets were detected in this PR.  
            Please review the workflow logs for details:  
            👉 [View Logs](${context.payload.pull_request.html_url}/checks)

            **Next steps:**
            - Remove or rotate the exposed credentials.
            - Force-push a cleaned commit (e.g. using \`git filter-repo\`).
            `;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: message
            });

            core.setFailed('Secrets detected by TruffleHog! Comment added to PR.');
